### ISSUE TITLE
[PATCH] The json name for the builder is "builder_name" and not  "builder".

### ISSUE THREAD

**Issue by nicdes** [suoto/hdl_checker#69]
---
 hdl_checker/base_server.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/hdl_checker/base_server.py b/hdl_checker/base_server.py
index cb990dc..44d8d40 100644
--- a/hdl_checker/base_server.py
+++ b/hdl_checker/base_server.py
@@ -225,7 +225,7 @@ class BaseServer(object):  # pylint: disable=useless-object-inheritance
 
         _logger.debug("Updating with base config:\n%s", pformat(config))
 
-        builder_name = config.pop("builder", None)
+        builder_name = config.pop("builder_name", None)
         if builder_name is not None:
             builder_cls = getBuilderByName(builder_name)
         else:
-- 
2.24.0

**Comment by suoto** [comment]
Ops, sorry about that. The idea was actually switch to `builder` instead of `builder_name`, namely to make it a bit clearer if/when supporting multiple compilers at the same time. (now on the correct issue!)
