### ISSUE TITLE
[PATCH] KeyError bug fixed in rebuildProject().

### ISSUE THREAD

**Issue by nicdes** [suoto/hdl_checker#70]
The dict servers has Path objects as key, not the project_file.

---
 hdl_checker/handlers.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/hdl_checker/handlers.py b/hdl_checker/handlers.py
index 9b363e1..a86fd86 100644
--- a/hdl_checker/handlers.py
+++ b/hdl_checker/handlers.py
@@ -236,7 +236,8 @@ def rebuildProject():
     server = _getServerByProjectFile(project_file)
     server.clean()
     _logger.debug("Removing and recreating server object")
-    del servers[project_file]
+    root_dir = Path(p.dirname(project_file))
+    del servers[root_dir]
     _getServerByProjectFile(project_file)
 
 
-- 
2.24.0

**Comment by suoto** [comment]
Ops, sorry about that. The idea was actually switch to `builder` instead of `builder_name`, namely to make it a bit clearer if/when supporting multiple compilers at the same time.
