### ISSUE TITLE
Error on Ubuntu 16.04 with Python 3.5

### ISSUE THREAD

**Issue by Tcenova** [suoto/hdl_checker#89]
After installing with pip3 on Ubuntu 16.04 the following error is encountered when running hdl_checker (with any options it seems)

```Traceback (most recent call last):
  File "/home/$USER/.local/bin/hdl_checker", line 5, in <module>
    from hdl_checker.server import main
  File "/home/$USER/.local/lib/python3.5/site-packages/hdl_checker/server.py", line 31, in <module>
    from hdl_checker import handlers, lsp
  File "/home/$USER/.local/lib/python3.5/site-packages/hdl_checker/lsp.py", line 167
    self._checker: Optional[Server] = None
                 ^
SyntaxError: invalid syntax
```

It looks like the syntax used was introduced in Python 3.6 (https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep526). setup.py does specify it works with 3.5 which does not seems to be the case.

**Comment by suoto** [comment]
You're right, thanks for spotting this, I'll fix setup file. I was hoping that there was a work around to get Python 3.5 working but could not find, sorry about that!
